server:
  port: 8083

spring:
  config:
    import:
    - .env[.properties]
  application:
    name: app-test
  datasource:
    url: ${DB_URL}
    username: ${DB_USUARIO}
    password: ${DB_CLAVE}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: "gpt-4o-mini"
          temperature: 0
          max-tokens: 1000
          top-p: 1.0
          presence-penalty: 0.0
          frequency-penalty: 0.0
      embedding:
        options:
          model: "text-embedding-3-small"
    vectorstore:
      pgvector:
        initialize-schema: true  #inicia tablas de pgvector automaticamente
        index-type: HNSW  #uses HNSW (Hierarchical Navigable Small World)
        distance-type: COSINE_DISTANCE
        dimensions: 1536  #define la dimension para vectores (OpenAI embeddings)
        max-document-batch-size: 10000  #maximo numero de documentos por insercion

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/insalud.log
    max-size: 10MB
